version: '3.5'

services:
  www:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123admin^&*
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123admin^&*
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: zuiaiqiansen@163.com
      PGADMIN_DEFAULT_PASSWORD: 123admin&*
      PGADMIN_LISTEN_PORT: 5431
    ports:
      - 5431:5431
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
