version: '3.5'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: f98c0D8*
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  sophia-api:
    image: sophia-api:0.0.1
    container_name: sophia-api
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - sophia:/sophia/api
    networks:
      - postgres

  sophia-www:
    image: sophia-www:0.0.1
    container_name: sophia-www
    restart: unless-stopped
    depends_on:
      - sophia-api
    volumes:
      - sophia:/sophia/api
    ports:
      - 80:80
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: zuiaiqiansen@163.com
      PGADMIN_DEFAULT_PASSWORD: f98c0D8
      PGADMIN_LISTEN_PORT: 5431
    ports:
      - 5431:5431
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
  sophia:
